spring.application.name=wms

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/wms_db
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=
